on:
  - push
  - workflow_dispatch
env:
  GRADLE_USER_HOME: ./cache
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_PASSWORD: ${{ secrets.PAT }}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ hashFiles('build.gradle.kts') }}
      - run: ./gradlew --build-cache dependencies
  test-and-publish-to-package:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ hashFiles('build.gradle.kts') }}
      - run: ./gradlew --build-cache dependencies --refresh-dependencies
      - run: ./gradlew spotlessCheck
      - run: ./gradlew test
      - run: ./gradlew publish